name: abcd
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /local/scratch/xkan/ABCD/abcd_rest-pearson-HCP2016.npy
time_seires: /local/scratch/xkan/ABCD/ABCD/abcd_rest-timeseires-HCP2016.npy
node_id: /local/scratch/xkan/ABCD/ids_HCP2016.txt
seires_id: /local/scratch/xkan/ABCD/ABCD/ids_HCP2016_timeseires.txt
label: /local/scratch/xkan/ABCD/ABCD/id2sex.txt

drop_last: True
stratified: True
cog_index: 0    # index of the predicted cog score
task: regression
comb_measures_path: /local/scratch3/khan58/Datasets/ABCD/labels37_final_comb_measures.csv
measure: sex


# Node Feature
node_feature_type: connection # identity, eigenvec, connection, centrality, degree_bin, orig_time_series, learnable_time_series, learnable_eigenvec, gnn_identity, gnn_eigenvec, gnn_connection
node_feature_dim: 360
node_feature_eigen_topk: 10   # Learnable eigenvector and gnn_eigenvect need this 
num_bins: 100


# learnable_time_series
time_series_hidden_size: 256
time_series_encoder: lstm
timeseries_embedding_type: last  # last or mean
timeseries_used_length: -1  # -1 means using all time points

feature_orig_or_sparse: orig  # orig, sparse, binary_sparse



# Sparse
sparse_ratio: 1

plot_figures: false  # whether plot figures (initial connectivity, attention etc.)

itype: fmri


binary_sparse: False
only_positive_corr: False

# gnn
gnn_hidden_channels: 256
gnn_num_layers: 2
gnn_pool: concat
gnn_num_heads: 2
gin_eps: 0.0
sage_aggr: mean   # mean, max, lstm


tune_gnn_hidden_channels: [256]
tune_gnn_num_layers: [2]
tune_gnn_pool: [concat]
tune_gnn_num_heads: [2]
tune_gin_eps: [0.0]
tune_sage_aggr: [mean]


