- name: SGD
  lr: 1e-4     # github default 1e-4, I previously used 5e-3, Actually, this lr is not used in the code
  match_rule: None
  except_rule: None
  no_weight_decay: false
  momentum: 0.9
  alpha: 0.1
  l1_ratio: 0.5


  lr_scheduler:
    mode: cos # ['step', 'poly', 'cos']
    base_lr: 1.0e-4   # default -4
    target_lr: 1.0e-5  # default -5

    decay_factor: 0.1 # for step mode
    milestones: [0.3, 0.6, 0.9]
    poly_power: 2.0 # for poly mode
    lr_decay: 0.98

    warm_up_from: 0.0
    warm_up_steps: 0

  
